### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by yuliangguo** [half-potato/ever_training#7]
I have seen this error in a reproducable way when running below command.  But why only on this scene, have no encounter such issue for other scenes?

python train.py -s /mnt/data_ssd_4tb/Datasets/zipnerf/undistorted/london/ --eval --images images_4

![Image](https://github.com/user-attachments/assets/a59963b1-2e65-4e0b-be16-712971e9646b)

**Comment by half-potato** [comment]
You might be running out of memory. Can you try —data_device cpu? Check the memory usage.

**Comment by yuliangguo** [comment]
It is not related to memory. The training has started, at such early stage

CPU: ~20G / 64G
GPU: ~2G / 24G

Could you try from your end to check if this is reproducible?

**Comment by half-potato** [comment]
This is reproducible. Very strange. Give me a bit of time to debug this.

**Comment by half-potato** [comment]
Okay should be fixed.

**Comment by yuliangguo** [comment]
Any new commit already?

**Comment by half-potato** [comment]
Right, forgot to update the submodule version. Should be updated now. The fix was in EVER.
